### ISSUE TITLE
Add support for regex in skipWords

### ISSUE THREAD

**Issue by kangax** [aotaduy/eslint-plugin-spellcheck#1]
For example, so that one could ignore spellchecking links in comments via something like `http://[^\s]*`

**Comment by aotaduy** [comment]
That could be a nice feature.
Maybe adding another option for regex ? 
Something like ``skipIfMatch ``
What do you think ?

**Comment by kangax** [comment]
Sure, `skipIfMatch` sounds like a good option too.

**Comment by aotaduy** [comment]
https://github.com/aotaduy/eslint-plugin-spellcheck/pull/2

**Comment by aotaduy** [comment]
Published in npm, please test
