### ISSUE TITLE
Stop using globals package

### ISSUE THREAD

**Issue by jrencz** [aotaduy/eslint-plugin-spellcheck#10]
It has been frozen (see: https://github.com/sindresorhus/globals/issues/82#issuecomment-201008770)

This plugin should be moved to some other mechanism. Preferably an extensible one.
I personally miss lodash method names, but the best I can do is to add them in `skipWords` :)

**Comment by aotaduy** [comment]
Will think in a solution for different environments besides Javascript, but for javascript i think that we should still use it.

**Comment by aotaduy** [comment]
Looks like globals package is still alive and new globals have been added lately I think we are going to use it until a new better approach emerges.
