### ISSUE TITLE
Handling proper name

### ISSUE THREAD

**Issue by kachkaev** [aotaduy/eslint-plugin-spellcheck#11]
Since the plugin started to lowercase the words before matching with the dictionary, proper names became marked as errors. E.g.
```js
const a = 'January', // You have a misspelled word January on String
```
I checked the dictionary used by the plugin – the names of the months are there.

The only solution I was able to get was in adding the lower-cased names of the months to ```.eslintrc```. This is not ideal since the list of the used proper names can sometimes can be pretty long.

**Comment by aotaduy** [comment]
We might add a solution as the one with ordinals, by checking first without changing case and then in another pass check with lowercase

**Comment by aotaduy** [comment]
This is solved!
