### ISSUE TITLE
Custom dictionaries

### ISSUE THREAD

**Issue by kachkaev** [aotaduy/eslint-plugin-spellcheck#12]
I'm wondering if it is possible to add a new config param with URLs to custom dictionaries. This will be extremely useful for projects that have UIs in other languages than English. Keeping thousands of words in `skipWords` does not seem to be an efficient way to solve this issue.

**Comment by aotaduy** [comment]
Yes i think it would be easy to add something like that. 
Let me check it out.

**Comment by kachkaev** [comment]
Great, thanks a lot for that! I was not having any particular dictionary to try, just was going to check out some `.dict` files on the web after the feature works (that's the only dictionary extension I have on top of my head).

**Comment by aotaduy** [comment]
Hi we have merged a Pull request to allow custom dictionaries. We have the British english dictionary as an example. Please check it out. https://github.com/aotaduy/eslint-plugin-spellcheck/pull/13/files Im going to publish the npm package tonight.

**Comment by aotaduy** [comment]
now you can add custom dictionaries to the rules/utils/dicts folder and then reference them from the lang property in the configuration.

**Comment by kachkaev** [comment]
Awesome! Would it be possible for you to update README.md as well please?

I'm wondering if anyone has ever shipped dictionaries as npm packages. Linking to something like `/node_modules/dictionary.en-gb/di` would be pretty cool! :–)
