### ISSUE TITLE
Automatically whitelist packages in manifest

### ISSUE THREAD

**Issue by mathieumg** [aotaduy/eslint-plugin-spellcheck#18]
Related to #10, it could be interesting to have an option that automatically whitelists any package used in the `package.json` file.

**Comment by aotaduy** [comment]
You mean the packages names or something else?
Thanks !

**Comment by mathieumg** [comment]
The package names. Sorry, had never seen your reply!

**Comment by aotaduy** [comment]
Good idea will add to features to work on
