### ISSUE TITLE
"You have a misspelled word: sreader"

### ISSUE THREAD

**Issue by jrencz** [aotaduy/eslint-plugin-spellcheck#19]
Line that causes the error:

```js
new RegExp(`\^Card\\sreader\\snot\\sconnected\\sin\\s${ numberOfSeconds }s\\.`);
```

This does not seem to be hackable with `skipIfMatch` since string has already been tokenized and `skipIfMatch` rules can't reach the `\\` (bare word `sreader` is matched against regular expressions created from `skipIfMatch` strings and this word is clearly misspelled.)

IMO this would have to be solved in core.

**Comment by aotaduy** [comment]
Solved with a bit of REGEXP magic! thanks
