### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by paazmaya** [aotaduy/eslint-plugin-spellcheck#20]
According to https://www.npmjs.com/package/eslint-plugin-spellcheck there seems to have been six releases so far.
However none of them have been tagged via git tags and hence are not listed at https://github.com/aotaduy/eslint-plugin-spellcheck/releases

How about tagging the releases?

```sh
git tag v0.0.2 ab0d20b874f8109e7056cbd01529a294bd3af031
git tag v0.0.3 532d34724a9def6ff886fc1a23f932a9fa5121c7
git tag v0.0.4 ea3feb408b8cdeb9c39c22c75e20bcf9d7911bcd
git tag v0.0.5 dc2adab29e361d69537eb65cafbdfed2cf0610ad
git tag v0.0.6 c3b669e2d7e59f47e492c8bb983e400080ad34e6
```

At least those I could gather based on the history of `package.json`.

Tags needs to be pushed separately, as they are not delivered by default:

```sh
git push --tags
```

The benefit of having releases tagged is to see the differences between them and since the last published release.

**Comment by aotaduy** [comment]
Cool, will do

**Comment by aotaduy** [comment]
Done thanks!
