### ISSUE TITLE
0.0.7 performance issue

### ISSUE THREAD

**Issue by jrencz** [aotaduy/eslint-plugin-spellcheck#21]
I recently tried to update `eslint-plugin-spellcheck` from 0.0.6 to 0.0.7 and I found out that after this update my lint task takes 4-5 times longer than before.

I have gulp-eslint installed so I have `gulp lint` task in my build process. I run it with `time` and here's what I got:

```
baseline: with spellcheck 0.0.6
gulp lint  66.09s   user 1.67s  system 100% cpu     1:07.31 total

test: with spellcheck 0.0.7
gulp lint  310.77s  user 5.91s  system 100% cpu     5:14.44 total
gulp lint  282.86s  user 5.52s  system 101% cpu     4:45.30 total
gulp lint  309.21s  user 5.97s  system 100% cpu     5:13.26 total
gulp lint  297.44s  user 5.71s  system 100% cpu     5:01.10 total
```

without any change in configuration.

**Comment by aotaduy** [comment]
I'm a bit short of time right now, but will try to review this one and the others these days.

**Comment by aotaduy** [comment]
I think that with latest changes v0.0.8 performance will go down. Will try to review and improve a bit.

**Comment by jrencz** [comment]
> I think that with latest changes v0.0.8 performance will go down. 

0.0.8 does not break performance worse than 0.0.7.

On 0.0.6 with my project currently:
gulp lint  50.74s user 1.31s system 102% cpu 50.619 total
gulp lint  50.54s user 1.62s system 99% cpu 52.214 total

On 07555a0 (latest commit on master, I'm not sure which commit is 0.0.8, there's no tag)
gulp lint  329.19s user 6.06s system 100% cpu 5:34.04 total

**Comment by Sam1301** [comment]
+ 1 facing the same issue

**Comment by aotaduy** [comment]
We have improved a little bit the performance replacing an Array with a Set, for inclusion check.
Check here https://github.com/aotaduy/eslint-plugin-spellcheck/pull/39
ANy other pull request is welcome, same for some way to test performance in the included tests.
We have a very primitive script now and we need some improvement.

**Comment by aotaduy** [comment]
I have addressed the original issue with performance please take a look at the 0.0.10 release. 
Is already published in npm
Looks like we where reading the dictionary a lot of times from file.
