### ISSUE TITLE
Test automation with Travis CI perhaps

### ISSUE THREAD

**Issue by paazmaya** [aotaduy/eslint-plugin-spellcheck#25]
Add `.travis.yml` file, login to https://travis-ci.org/ and enable this repository over there.

Can do PR for the file.

**Comment by aotaduy** [comment]
Thanks for the PR !

**Comment by paazmaya** [comment]
It still needs to be enabled and perhaps a badge to be placed in the `README.md`

**Comment by aotaduy** [comment]
Yes is done !

**Comment by paazmaya** [comment]
Now nice!
