### ISSUE TITLE
Exclude files from npm package

### ISSUE THREAD

**Issue by paazmaya** [aotaduy/eslint-plugin-spellcheck#27]
In order to make downloads faster, exclude files that are not needed for the plugin to work from the npm package, such as the test files.

Currently the size of the npm package is 638 KB, via `npm pack` command.
While it is not huge, I will create a PR (#hacktoberfest) to see how much smaller it can get.

**Comment by aotaduy** [comment]
I think that our space problem is with dictionaries. For the ease of use of the plugin I added some of the available dictionaries directly to the plugin. Maybe with some download mechanism we could decrease the file size. But i would like to have something that maintains the ease of configuration.
