### ISSUE TITLE
Strings inside of require() fail check

### ISSUE THREAD

**Issue by sedenardi** [aotaduy/eslint-plugin-spellcheck#3]
Is there a way to have the plugin ignore strings inside of require() statements, as most of mine are either node libraries or path names, which are sure to fail spellchecks. Thanks in advance.

**Comment by aotaduy** [comment]
Have you tried with the ``skipIfMatch``  ?
Could you provide some examples for some failing lines to better check an option for your case?
Thanks !

**Comment by sedenardi** [comment]
@aotaduy I apologize for not seeing your reply sooner, didn't mean to leave you hanging.

An example of a failing line is:
`var lodash = require('lodash');`
With the default options I get the message "You have a misspelled word: lodash on String". I know if I add "lodash" to the `skipIfMatch` array then it'll pass, but then I'd have to do this for every module that fails the spell check, and could get unmanageable rather quickly.

Any thoughts?

**Comment by aotaduy** [comment]
In the current version the only way os to add them to the skipsWords or skipIfMatch configuration arrays. But lets think in some other way to add as a feature.

**Comment by sedenardi** [comment]
Would it work to do a regex search on an entire statement? So, if your regex pattern were `/require\(/`, then the line `var lodash = require('lodash');` would be excluded.

Thanks for your help. Sorry again for the lapse in communication.

**Comment by aotaduy** [comment]
It wouldn't work, because the skipIfMatch is being checked against the Javascript language parsed node such as Literal string, Variable, or Comment. 
We might try to add it as a new feature something like `skipLinesIfMatch` so we can skip the entire line if the regexp matches. 

No problem I have a busy day too.

**Comment by sedenardi** [comment]
Makes sense. 

Now I'm inspired to dig around and learn about what's going on under the hood of eslint plugins.

**Comment by aotaduy** [comment]
Give it a chance. This one is a small and quite simple example of a plugin.

**Comment by aotaduy** [comment]
I'm open to pull requests if you want to collaborate with this functionality. It will be nice to add the feature.
