### ISSUE TITLE
Document purpose of number in config array

### ISSUE THREAD

**Issue by DavidRieman** [aotaduy/eslint-plugin-spellcheck#31]
Through trial and error, I found the number in the configuration:
`"spellcheck/spell-checker": [1, ...`
Seems to me to have the behaviors "0 to disable all, 1 to produce warnings, or 2 to produce errors".  It would be handy to verify this, or other possible options (if any), in the readme.md.

**Comment by aotaduy** [comment]
Oh, that is a default for eslint rules, check http://eslint.org/docs/user-guide/configuring we could copy and paste or add a link to explain the number.

**Comment by DavidRieman** [comment]
I think brief sentence at the end of the opening configuration section, with the link would be sufficient to help others.  (I suspect this will be the first encounter with ESLint plugins for many seeking these capabilities.)  Maybe:  
> This ESLint plugin, like others, can be reconfigured to produce errors (2), warnings (1), or disabled (0) with the first numeric argument.  For more information on ESLint configuration, see: http://eslint.org/docs/user-guide/configuring

**Comment by aotaduy** [comment]
I'll add your paragraph. 
Thank you !
