### ISSUE TITLE
Allow skipWords to read from a file

### ISSUE THREAD

**Issue by skarfacegc** [aotaduy/eslint-plugin-spellcheck#32]
I have a list of words to skip (spell checking documentation in addition to code)
is it possible to use a single file with a list of words instead of adding to skiplist?

**Comment by aotaduy** [comment]
Is not possible now, is the list too big, why do you have it in a separate file?

**Comment by Middlerun** [comment]
If you define your eslintrc in JS, you can do this:

```
const path = require('path');
const fs  = require("fs");

const spellingWhitelist = fs.readFileSync(path.join(__dirname, 'spellingWhitelist.txt'))
  .toString()
  .split('\n')
  .map(word => word.replace(/\/\/.*$/, ''))  // So you can add comments to the words
  .map(word => word.trim())  // Remove any leading/trailing whitespace
  .filter(word => word);  // Remove any empty lines

module.exports = {
  plugins: ['spellcheck'],
  rules: {
    "spellcheck/spell-checker": [1,
      {
        skipWords: spellingWhitelist,
      }
    ],
  },
};
```

**Comment by aotaduy** [comment]
nice ! I think this resolves the issue by using an existing feature from eslint. @Middlerun would you mind to create a PR to update the docs in order to add this option ? Coould it be a link to this issue.
