### ISSUE TITLE
skipWords for md5, sha256, sha1

### ISSUE THREAD

**Issue by oatkiller** [aotaduy/eslint-plugin-spellcheck#35]
Hey thanks for making this package. I am trying to tune it for our code base and I've come across an issue where I can't skip the words:
* md5
* sha1
* sha256

They are found in identifiers, camelcased, like 'myFavSha256' or 'someMd5' and it is there that things fall apart.

I've tried adding the following things to skipWords:
* 'Sha256',
* 'sha256',
* 'SHA256',
* etc

Please let me know if there is an easy work around. If an example code base helps, let me know and I will work something up.
Thanks!

**Comment by rseymour** [comment]
why not use skipIfMatch?

**Comment by oatkiller** [comment]
@rseymour My understanding is that skipIfMatch would cause the entire string, identifier, or comment to be ignored.

**Comment by aotaduy** [comment]
You can give a try to our recent contributed feature:

"skipWordIfMatch": <<Array Of Strings>> default: []
Array of Regular Expressions the plugin will try to match every single word that is found in the nodes (identifier, comment, string, string template, etc) and will not check the single word if matched.
i.e: "^[-\\w]+\/[-\\w\\.]+$" will ignore MIME types.

Check the readme

**Comment by romaric-juniet** [comment]
I've had this issue with Keccak256, the solution was to skip `keccak` and not `keccak256`:
```
"skipWords": [
  "keccak",
],
```
Would be good to have this case fixed or explained in the doc though

**Comment by aotaduy** [comment]
Could you write a paragraph to add to the documentation? 
You an add it here and i will happily update the Readme file. 

The case is that we separate the words in between numbers, separators and different case to be able to check  each word separatedly. 

Thanks!

**Comment by romaric-juniet** [comment]
Sure, happy to help. I created a PR
