### ISSUE TITLE
JSDoc keywords

### ISSUE THREAD

**Issue by kachkaev** [aotaduy/eslint-plugin-spellcheck#4]
Hi aotaduy,

Thank you for the plugin! One quick question: I'm using JSDoc and hence have keywords like [@param etc.](http://usejsdoc.org/) in my comments. The plugin marks some of them as misspelled words. Any global workaround?

**Comment by aotaduy** [comment]
To workaround this you should add the words to skipWords or a regexp to skipIfMatch parameters for the project.

**Comment by kachkaev** [comment]
OK, makes sense. I tried to build such a list of skipWords based on the keywords mentioned on [usejsdoc.org](http://usejsdoc.org/). Hope it helps someone with the same problem.

```json
[
  "jsdoc",

  "classdesc",
  "enum",
  "inheritdoc",
  "memberof",
  "mixin",
  "namespace",
  "param",
  "readonly",
  "todo",
  "typedef"
]
```

**Comment by aotaduy** [comment]
Cool will add those to the default configuration. 
Thank you !
