### ISSUE TITLE
broken link for this pkg on npmjs.com

### ISSUE THREAD

**Issue by techieshark** [aotaduy/eslint-plugin-spellcheck#41]
Viewing https://www.npmjs.com/package/eslint-plugin-spellcheck, the "homepage" link goes to: https://github.com/sotaduy/eslint-plugin-spellcheck. `sotaduy` should be `aotaduy`.

![image](https://user-images.githubusercontent.com/1072292/39971810-0930d2ce-56b7-11e8-8e0a-db1bb584f09e.png)

**Comment by krutoo** [comment]
Hi. It is still actual?

**Comment by aotaduy** [comment]
This is fixed!
