### ISSUE TITLE
Allow ignoring paths or selecting specific paths

### ISSUE THREAD

**Issue by Sharabesh** [aotaduy/eslint-plugin-spellcheck#58]
Looks like there's currently not a great option to ignore specific paths for this module or select specific paths to run on.

**Comment by aotaduy** [comment]
Sorry but I dont understand what wyou mean. Could you explain a little bit more on this?

**Comment by aotaduy** [comment]
You can do this at the eslint level, but not in the plugin level check https://eslint.org/docs/user-guide/configuring/ignoring-code
