### ISSUE TITLE
spellCheck inside template strings

### ISSUE THREAD

**Issue by kachkaev** [aotaduy/eslint-plugin-spellcheck#6]
I've noticed that a plugin does not look into ES6 template strings, which are surrounded by \` \`.

![screen shot 2016-02-09 at 10 03 35](https://cloud.githubusercontent.com/assets/608862/12913076/7d66978c-cf14-11e5-947f-7ac2cca51218.png)

Hope this is not difficult to fix it.

**Comment by aotaduy** [comment]
Will Check it out Alexander. I haven't tested the plugin against ES6 code.

**Comment by aotaduy** [comment]
You are right Alexander! Is not checking the strings inside templates, I'm working on a fix.
Thanks!

**Comment by aotaduy** [comment]
Published the update

**Comment by kachkaev** [comment]
Fantastic! Thanks!
