### ISSUE TITLE
"decrement" should pass

### ISSUE THREAD

**Issue by laviro** [aotaduy/eslint-plugin-spellcheck#67]
Looks like decrement is a valid English word, see also: https://dictionary.cambridge.org/dictionary/english/decrement

but I am still getting a warning about it with the plugin: `You have a misspelled word: decrement on String  spellcheck/spell-checker`

**Comment by aotaduy** [comment]
I think we might have an outdated dictionary, you can use your own dictionary by using langDir option or, skip the word with a skipWord in the configuration
