### ISSUE TITLE
Does this plugin support html files?

### ISSUE THREAD

**Issue by s4m0r4m4** [aotaduy/eslint-plugin-spellcheck#76]

**Comment by aotaduy** [comment]
I dont think, so. Maybe you can manage to make it work to spellcheck javascript embedded in html but I haven't tested it yet.

**Comment by s4m0r4m4** [comment]
Ok, thanks for the quick reply! I'm not sure if that's an eslint limitation or something specific to this plugin, but boy would that be helpful for web applications, where a good deal of user-facing text is in html files.

**Comment by aotaduy** [comment]
Maybe you can cspell a chance https://streetsidesoftware.github.io/cspell/docs/getting-started/
