### ISSUE TITLE
Mimetypes should be ignored

### ISSUE THREAD

**Issue by jrencz** [aotaduy/eslint-plugin-spellcheck#9]
Ad-hoc solution

```json
"skipIfMatch": [
  // mime types (with application/vnd.<string>)
  "^[-\\w]+\/[-\\w\\.]+$"
]
```

**Comment by aotaduy** [comment]
I think that for this case we should stick to your add hoc solution, I will use it as an example for skipIfMatch.

**Comment by aotaduy** [comment]
I added your example to the readme.
